services:
  - type: web
    name: angular-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/YOUR_PROJECT_NAME
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
